# Generated by Django 5.0.3 on 2024-04-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_category_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
